#Especifica qual imagem docker pode ser utilizada. 
#image: node:19.1


stages:
  - teste
  - build
  - deploy

executar_teste:
  stage: teste
  before_script:
    - echo "Preparando teste..."
    - chmod +x ./script.sh
  script:
    - ./script.sh
  after_script:
    - echo "Apagando arquivos temporários..."

criar_imagens:
  stage: build
  script:
    - echo "Criando as images..."
    - ls
    - cat /etc/os-release

executar_teste2:
  #Especifica qual imagem docker pode ser utilizada em um job especifico. 
  image: node:19.1
  stage: teste
  script:
    - echo "Executando teste 2..."
    - npm version
push_imagens:
  needs:
    - criar_imagens
  stage: build
  script:
    - echo "Realizando upload das images..."
docker:
  stage: deploy
  script: 
    - echo "Executando deploy" 